[theme]
primaryColor = "#4A90E2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#2D3748"

[server]
headless = true
enableCORS = false
port = 8501

[browser]
gatherUsageStats = false